import Head from 'next/head';
import Link from 'next/link';

import { scrollTop } from '../public/utils';

import AlbumWall from '../components/AlbumWall';
import SpaceCard from '../components/SpaceCard';
import LinkBubble from '../components/LinkBubble';
import HomeSearch from '../components/HomeSearch';
import Navigation from '../components/Navigation';
import ProductCard from '../components/ProductCard';
import ServiceCard from '../components/ServiceCard';
import CategoryCard from '../components/CategoryCard';
import ThemeSaleCard from '../components/ThemeSaleCard';
import HomeFooter from '../components/footers/HomeFooter';

import User from '../components/icons/User';
import ArrowRight from '../components/icons/ArrowRight';
import CaretUpFilled from '../components/icons/CaretUpFilled';

import themeRoom1 from '../public/assets/pngs/theme-room1.png';
import themeRoom2 from '../public/assets/pngs/theme-room2.png';
import productImage1 from '../public/assets/pngs/product1.png';
import productImage2 from '../public/assets/pngs/product2.png';
import productImage3 from '../public/assets/pngs/product3.png';

const PRODUCTS = [
  {
    _id: 1,
    price: 2.99,
    name: 'GURLI',
    image: productImage1,
    type: 'Cushion cover',
    createdAt: '2023-01-21T10:13:00.000Z',
    updatedAt: '2023-01-21T10:13:00.000Z',
  },
  {
    _id: 2,
    price: 2.99,
    name: 'GURLI',
    image: productImage2,
    type: 'Cushion cover',
    createdAt: '2022-12-30T10:13:00.000Z',
    updatedAt: '2022-12-30T10:13:00.000Z',
  },
  {
    _id: 3,
    price: 2.99,
    name: 'GURLI',
    image: productImage3,
    type: 'Cushion cover',
    createdAt: '2022-12-11T10:13:00.000Z',
    updatedAt: '2022-12-11T10:13:00.000Z',
  },
  {
    _id: 4,
    price: 2.99,
    name: 'GURLI',
    image: productImage1,
    type: 'Cushion cover',
    createdAt: '2022-12-11T10:13:00.000Z',
    updatedAt: '2022-12-11T10:13:00.000Z',
  },
];

const CATEGORIES = [
  {
    _id: 1,
    categoryName: 'armchairs',
    className: 'bg-[url(/assets/pngs/product3.png)]',
  },
  {
    _id: 2,
    categoryName: 'tables',
    className: 'bg-[url(/assets/pngs/table.png)]',
  },
  {
    _id: 3,
    categoryName: 'bed',
    className: 'bg-[]',
  },
  {
    _id: 4,
    categoryName: 'wardrobes',
    className: 'bg-[url(/assets/pngs/wardrobe.png)]',
  },
];

const THEME_SALES = [
  {
    _id: 1,
    image: themeRoom1,
    title: 'Gurli Gurli Gurli Gurli',
    description:
      'Find gifts from a few euros. Ideal with the holidays just around the corner. Shop now.',
  },
  {
    _id: 2,
    image: themeRoom2,
    title: 'Gurli Gurli Gurli Gurli',
    description:
      'Find gifts from a few euros. Ideal with the holidays just around the corner. Shop now.',
  },
  {
    _id: 3,
    image: themeRoom1,
    title: 'Gurli Gurli Gurli Gurli',
    description:
      'Find gifts from a few euros. Ideal with the holidays just around the corner. Shop now.',
  },
  {
    _id: 4,
    image: themeRoom2,
    title: 'Gurli Gurli Gurli Gurli',
    description:
      'Find gifts from a few euros. Ideal with the holidays just around the corner. Shop now.',
  },
];

const SPACE_IDEAS = [
  { _id: 1, className: 'bg-[url(/assets/pngs/space1.png)]', title: 'Maximizing your space' },
  { _id: 2, className: 'bg-[url(/assets/pngs/space2.png)]', title: 'Personalizing your workspace' },
  { _id: 3, className: 'bg-[url(/assets/pngs/space1.png)]', title: 'Maximizing your space' },
  { _id: 4, className: 'bg-[url(/assets/pngs/space2.png)]', title: 'Personalizing your workspace' },
];

const SERVICES = [
  {
    href: '/',
    title: 'Smart Search & Personalized Filter',
    description:
      'We use the smart technology to understand the intent and context of your search and filter for your specifications',
  },
  {
    href: '/',
    title: 'AR & AI',
    description:
      "We've adopted augmented reality and artificial intelligence to enhance your overall shopping experience",
  },
  {
    href: '/',
    title: 'Customer Service',
    description: 'Find out the solutions to your questions',
  },
  {
    href: '/',
    title: 'Pickups & Delivery',
    description: 'We primarily use delivery service to get your goods safely home.',
  },
];

const Home = ({ products }) => {
  const subNavButtons = [
    { text: 'home', href: '/' },
    { text: 'categories', href: '/' },
    { text: 'themes', href: '/' },
    { text: 'rooms', href: '/' },
    { text: 'sales', href: '/' },
  ];

  const headerTexts = ['Delivery only', 'Customer Service', 'Campaign'];

  return (
    <>
      <Head>
        <title>Avni - Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Navigation extraStyles={{ top: '65px', position: 'absolute' }} />

      <div className='bg-wild-sand text-outer-space text-[12px] leading-[15px] font-medium tracking-[0.36px] h-[35px] flex items-center justify-center gap-[30px]'>
        {headerTexts.map(text => (
          <div
            key={text}
            className='flex gap-x-[10px] items-center justify-center h-full px-[10px]'
          >
            <div className='border-2 w-3 h-3 rounded-full border-azure-radiance' />
            {text}
          </div>
        ))}
      </div>

      <main className='font-medium tracking-[0.36px] mx-[15%] mt-[250px]'>
        <header className='text-[12px] leading-[15px] w-max mx-auto absolute top-[85px] left-1/2 -translate-x-1/2 z-[70]'>
          <div className='flex gap-x-[25px] items-center h-[46px] mx-auto'>
            <HomeSearch />

            <button className='bg-[url(/assets/svgs/cart.svg)] bg-center bg-no-repeat bg-wild-sand w-[46px] h-full rounded-full' />

            <button className='bg-[url(/assets/svgs/heart.svg)] bg-center bg-no-repeat bg-wild-sand w-[46px] h-full rounded-full' />
          </div>

          <div className='flex gap-x-5 items-start justify-between pt-5 mt-6 border-t-[1px] border-wild-sand mx-auto'>
            {subNavButtons.map(({ text, href }) => (
              <button
                key={text}
                onClick={null}
                className='capitalize h-[39px] px-[25px] bg-wild-sand rounded-[40px] text-outer-space'
              >
                {text}
              </button>
            ))}
            <Link
              href='/'
              className='flex gap-x-[10px] py-3 px-5 ml-[100px] rounded-[30px] border-[1px] border-alto-light'
            >
              <User />
              Sign in or Sign up
            </Link>
          </div>

          <h1 className='text-[24px] leading-[29px] mt-[90px]'>Welcome back!</h1>

          <h2 className='text-[14px] leading-[21px] text-light-dove-gray mt-[17px]'>
            We are on a mission to get your perfect piece! Anticipate the smile that comes at your
            items' arrival 😁
          </h2>

          <h3 className='text-[18px] leading-[22px] mt-[50px]'>Award winning products</h3>
          <LinkBubble extraStyles={{ marginLeft: '0' }} href='/' text='View all' />
        </header>

        <section className='relative mt-[535px]'>
          <div className='x-scroll flex gap-x-[5px] overflow-x-scroll pb-[30px]'>
            {products.map(({ name, type, price, image, _id }) => (
              <ProductCard
                key={_id}
                productName={name}
                productType={type}
                productPrice={price}
                productImage={image}
              />
            ))}
          </div>

          <button
            onClick={null}
            className='absolute z-50 top-1/2 -translate-y-1/2 -right-[27px] box-content border-[10px] border-white grid place-items-center text-white bg-zorba w-[35px] h-[35px] rounded-full dark:border-shark dark:bg-white dark:text-zorba'
          >
            <ArrowRight />
          </button>
        </section>

        <section className='mt-[200px] h-[560px] grid grid-cols-[40%_24%_36%] grid-flow-col grid-rows-[repeat(560,1px)]'>
          <div className='bg-alto bg-[url(/assets/pngs/decoration1.png)] bg-cover bg-center bg-no-repeat row-start-1 row-end-[560] flex items-center justify-center flex-col gap-y-[100px]'>
            <div className='ripple' />
            <div className='ripple' />
          </div>

          <div className='bg-zorba row-start-1 row-end-[338] font-bold px-[15%] flex flex-col gap-y-5 items-center justify-center'>
            <p className='text-[16px] leading-5 text-[rgba(255,255,255,0.5)]'>
              Trending Product Categories
            </p>
            <p className='text-[14px] leading-[17px] text-white'>
              Get inspired with what others are buying...
            </p>
          </div>
          <div className='bg-silver-chalice grid place-items-center row-start-[338] row-end-[560] bg-[url(/assets/pngs/decoration2.png)] bg-no-repeat bg-cover bg-center'>
            <div className='ripple' />
          </div>

          <div className='bg-dorado bg-[url(/assets/pngs/decoration3.png)] bg-cover bg-center bg-no-repeat row-start-1 row-end-[196] flex items-center justify-center gap-x-[20%]'>
            <div className='ripple' />
            <div className='ripple' />
          </div>
          <div className='bg-boulder bg-[url(/assets/pngs/decoration4.png)] bg-cover bg-center bg-no-repeat row-start-[196] row-end-[560] grid place-items-center'>
            <div className='ripple' />
          </div>
        </section>

        <section className='mt-[200px] text-center'>
          <h4 className='text-[18px] leading-[22px]'>Categories</h4>

          <div className='relative mt-[84px]'>
            <div className='x-scroll flex gap-x-[5px] overflow-x-scroll pb-[30px]'>
              {CATEGORIES.map(({ _id, categoryName, className }) => (
                <CategoryCard key={_id} categoryName={categoryName} className={className} />
              ))}
            </div>

            <button
              onClick={null}
              className='absolute z-50 top-1/2 -translate-y-1/2 -right-[27px] box-content border-[10px] border-white grid place-items-center text-white bg-zorba w-[35px] h-[35px] rounded-full dark:border-shark dark:bg-white dark:text-zorba'
            >
              <ArrowRight />
            </button>
          </div>
        </section>

        <section className='mt-[200px] text-center'>
          <h5 className='text-[18px] leading-[22px]'>Theme sales</h5>

          <div className='relative mt-[84px]'>
            <div className='x-scroll flex gap-x-[5px] overflow-x-scroll pb-[30px]'>
              {THEME_SALES.map(({ _id, image, title, description }) => (
                <ThemeSaleCard
                  key={_id}
                  themeTitle={title}
                  themeImage={image}
                  themeDescription={description}
                />
              ))}
            </div>

            <button
              onClick={null}
              className='absolute z-50 top-1/2 -translate-y-1/2 -right-[27px] box-content border-[10px] border-white grid place-items-center text-white bg-zorba w-[35px] h-[35px] rounded-full dark:border-shark dark:bg-white dark:text-zorba'
            >
              <ArrowRight />
            </button>
          </div>
        </section>

        <section className='mt-[200px] text-center'>
          <h6>Ideas for your space</h6>

          <div className='relative mt-[84px]'>
            <div className='x-scroll flex gap-x-[5px] overflow-x-scroll pb-[30px]'>
              {SPACE_IDEAS.map(({ _id, className, title }) => (
                <SpaceCard key={_id} className={className} title={title} />
              ))}
            </div>

            <button
              onClick={null}
              className='absolute z-50 top-1/2 -translate-y-1/2 -right-[27px] box-content border-[10px] border-white grid place-items-center text-white bg-zorba w-[35px] h-[35px] rounded-full dark:border-shark dark:bg-white dark:text-zorba'
            >
              <ArrowRight />
            </button>
          </div>
        </section>

        <section className='mt-[200px] grid grid-rows-[repeat(2,150px)] grid-cols-2 grid-flow-row gap-x-[21px] gap-y-[17px]'>
          {SERVICES.map(({ title, href, description }) => (
            <ServiceCard key={title} title={title} description={description} href={href} />
          ))}
        </section>

        <section className='mt-[200px] text-center pb-[60px]'>
          <h6 className='text-[18px] leading-[22px]'>Social Reviews</h6>

          <p className='mt-[18px] text-light-dove-gray text-[14px] leading-[21px] dark:text-[rgba(255,255,255,0.6)]'>
            Get featured in our social album.
            <br />
            How does our furniture look in your space? Share your images using the hashtag
            #avnifurniture or tag @furniture.avniverse
          </p>

          <AlbumWall />

          <Link
            href='/'
            className='inline-block mt-[45px] py-3 px-5 text-[12px] leading-[15px] rounded-[30px] border-[1px] border-alto-light'
          >
            View more
          </Link>
        </section>

        <button
          onClick={scrollTop}
          className='bg-outer-space w-10 h-10 top-5 relative left-[calc(100%+30px)] rounded-full grid place-items-center text-wild-sand dark:bg-wild-sand dark:text-outer-space phones:w-10 phones:h-10 phones:left-[90%]'
        >
          <CaretUpFilled />
        </button>

        <HomeFooter />
      </main>
    </>
  );
};

export async function getServerSideProps() {
  // fetch proucts data from API
  return {
    props: { products: PRODUCTS },
  };
}

export default Home;
