import Head from 'next/head';
import Image from 'next/image';

import Slider from '../components/Slider';
import Footer from '../components/Footer';
import TextSlider from '../components/TextSlider';
import LinkBubble from '../components/LinkBubble';
import HistorySlider from '../components/HistorySlider';
import CurlyArrow from '../components/icons/CurlyArrow';
import CaretUpFilled from '../components/icons/CaretUpFilled';

import pause from '../public/assets/svgs/pause2.svg';
import slide1 from '../public/assets/pngs/slide1.png';
import slide2 from '../public/assets/pngs/slide2.png';
import slide3 from '../public/assets/pngs/slide3.png';
import testVideo from '../public/assets/test-video.mp4';
import furniture1 from '../public/assets/pngs/furniture1.png';
import furniture2 from '../public/assets/pngs/furniture2.png';
import furniture3 from '../public/assets/pngs/furniture3.png';
import furniture4 from '../public/assets/pngs/furniture4.png';
import newsHeadMedia from '../public/assets/pngs/news-head.png';
import newsBodyMedia from '../public/assets/pngs/news-body.png';

import { scrollTop } from '../public/utils';

const slidesData = [
  {
    _id: 1,
    image: slide1,
    video: null,
    title: 'Shop now',
    focalPoints: [
      { x: 20, y: 54 },
      { x: 35, y: 60 },
      { x: 70, y: 48 },
    ],
    themeColor: '#232b2b',
  },
  {
    _id: 2,
    image: null,
    video: testVideo,
    thumbnail: slide2,
    title: 'Why we are different',
    focalPoints: [],
    themeColor: '#b68e5c',
  },
  {
    _id: 3,
    image: slide3,
    video: null,
    title: 'Getting real with us',
    focalPoints: [
      { x: 12, y: 73 },
      { x: 48, y: 21 },
      { x: 85, y: 47 },
    ],
    themeColor: '#187789',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Avni</title>
        <meta charSet='UTF-8' />
        <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />

        <link rel='apple-touch-icon' sizes='180x180' href='/favicons/apple-touch-icon.png' />
        <link rel='icon' type='image/png' sizes='32x32' href='/favicons/favicon-32x32.png' />
        <link rel='icon' type='image/png' sizes='16x16' href='/favicons/favicon-16x16.png' />
        <link rel='manifest' href='/favicons/site.webmanifest' />
        <link rel='mask-icon' href='/favicons/safari-pinned-tab.svg' color='#5bbad5' />
        <meta name='msapplication-TileColor' content='#da532c' />
        <meta name='theme-color' content='#ffffff' />
      </Head>

      <main>
        <header className='mt-20 font-medium'>
          <h1 className='text-[42px] leading-[60px] text-center max-w-[387px] mx-auto'>
            A mission to get your perfect piece
          </h1>

          <LinkBubble text='Go Shopping' href='/home' />
        </header>

        <div className='mx-[14%] mt-[5%]'>
          <Slider slidesData={slidesData} />

          <section className='grid grid-rows-[repeat(2,auto)] grid-cols-2 gap-y-[87px] mt-52 tracking-[0.36px] font-medium'>
            <h2 className='text-[30px] leading-[45px] max-w-[80%]'>
              What others are saying about us
            </h2>
            <p className='text-[14px] leading-5 max-w-[70%] ml-auto'>
              We are not your regular retail store. Behind every piece is a promise kept.
              That&apos;s why people can&apos;t stop talking about us
              <hr className='border-alto-light w-[35%] mt-[30px]' />
            </p>
            <div className='h-[560px] bg-[url(/assets/pngs/customers.png)] bg-cover bg-center bg-no-repeat col-start-1 col-end-3 flex items-end'>
              <p className='w-full h-[18%] py-7 pl-7 text-white text-[14px] leading-[17px] bg-[rgba(35,43,43,0.1)] backdrop-blur-[2px]'>
                <span className='block font-bold'>Testimonials</span>
                <span className='block mt-[10px]'>
                  Client stories / experience, social media reviews, ...
                </span>
              </p>

              <button className='bg-[url(/assets/svgs/play.svg)] h-[18%] aspect-square py-7 bg-white bg-no-repeat bg-center' />
            </div>
          </section>

          <HistorySlider />

          <section className='mt-52 tracking-[0.36px] font-medium'>
            <h3 className='text-[30px] leading-[45px] text-center'>
              Furniture solution on a budget
            </h3>
            <Image src={furniture1} className='mt-20' alt='furniture1' />
            <p className='relative left-[5%] bottom-12 font-semibold text-[16px] leading-[100%] text-white'>
              A budget furniture requirement of a new couple
            </p>

            <div className='relative mt-52'>
              <Image src={furniture2} alt='furniture2' />
              <div className='bg-[rgba(0,0,0,0.2)] backdrop-blur-[72px] flex items-center justify-between w-full absolute bottom-0 py-14 px-[60px]'>
                <p className='font-semibold text-[32px] leading-10 max-w-[348px] text-white'>
                  Ideas for a cool living space
                </p>
                <button className='bg-white rounded-full text-cod-gray font-medium text-[12px] leading-4 py-[15px] px-[30px]'>
                  Visit
                </button>
              </div>
            </div>
          </section>

          <section className='mt-52 tracking-[0.36px] font-medium'>
            <h3 className='text-[30px] leading-[45px] text-center'>Space Ideas</h3>
            <div className='grid grid-cols-[77%_23%] mt-20 h-[560px]'>
              <div className='relative'>
                <Image src={furniture3} className='w-full h-full' alt='furniture3' />
                <button className='absolute right-0 top-0 w-[6%] h-full bg-[url(/assets/svgs/double-caret-right.svg)] bg-no-repeat bg-center bg-[rgba(0,0,0,0.2)] backdrop-blur-[72px]' />
              </div>
              <div className='bg-[url(/assets/pngs/furniture4.png)] bg-no-repeat bg-cover bg-center transition-all duration-500' />
            </div>
          </section>

          <section className='mt-52 font-medium tracking-[0.36px]'>
            <h3 className='text-[30px] leading-[45px] text-center'>Our environment and Us</h3>
            <p className='text-[14px] leading-5 text-center max-w-[632px] mx-auto mt-[18px] mb-[30px]'>
              We are conscious of the impact of furniture making on our environment. At Avni, our
              goal is to promote eco-friendly furniture for you, for us and for our environment.
            </p>

            <LinkBubble text="Here's how" href='/home' />

            <Image
              src={newsHeadMedia}
              alt='avni news header'
              className='w-full h-full mt-[84px] mb-[26px]'
            />
            <CurlyArrow extraStyles={{ marginLeft: 'auto', marginRight: '15%' }} />
          </section>

          <section className='mt-[26px] mb-8 h-[734px] grid grid-cols-2'>
            <TextSlider pretext='We are conscious of the impact of furniture making on our environment. From Global warming, to Deforestation, to' />

            <div className='relative h-max'>
              <Image src={newsBodyMedia} className='w-[498px] h-[560px]' alt='avni news body' />
              <button className='w-[50px] h-[50px] bg-white absolute bottom-4 right-4 grid place-items-center rounded-full'>
                <Image src={pause} alt='pause' />
              </button>
            </div>

            <button
              onClick={scrollTop}
              className='bg-outer-space w-8 h-8 col-start-2 relative left-full top-[120%] rounded-full grid place-items-center text-wild-sand dark:bg-wild-sand dark:text-outer-space'
            >
              <CaretUpFilled />
            </button>
          </section>

          <Footer />
        </div>
      </main>
    </>
  );
}
